export default {
  JOIN: "JOIN",
  START: "START",
  LEAVE: "LEAVE",
  CORRECT: "CORRECT",
  WRONG: "WRONG",
  VALIDATE: "VALIDATE",
  RESULT: "RESULT",
  HELLO: "HELLO",
  HI: "HI",
  LOSTCONNECTION: "LOSTCONNECTION",
  HEARTBEAT: "HEARTBEAT", // 心跳检测
};
