export default {
  HELLO: "HELLO",
  HI: "HI",
  JOIN: "JOIN",
  JOIN_SUCCESS: "JOIN_SUCCESS",
  JOIN_FAILED: "JOIN_FAILED",
  START: "START",
  NEXT_TITLE: "NEXT_TITLE",
  LEAVE: "LEAVE",
  CHOICE: "CHOICE",
  MOVEMENT: "MOVEMENT",
  VALIDATE: "VALIDATE",
  OVER: "OVER",
  LOGIN_FAILED: "LOGIN_FAILED",
  HEARTBEAT: "HEARTBEAT", // 心跳检测
};
